/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/floatSearchIndex.ts
var floatSearchIndex_exports = {};
__export(floatSearchIndex_exports, {
  default: () => FloatSearchPlugin
});
module.exports = __toCommonJS(floatSearchIndex_exports);
var import_obsidian2 = require("obsidian");

// src/leafView.ts
var import_obsidian = require("obsidian");
var popovers = /* @__PURE__ */ new WeakMap();
function isEmebeddedLeaf(leaf) {
  return leaf.containerEl.matches(".fs-block.fs-leaf-view .workspace-leaf");
}
function genId(size) {
  const chars = [];
  for (let n = 0; n < size; n++)
    chars.push((16 * Math.random() | 0).toString(16));
  return chars.join("");
}
function nosuper(base) {
  const derived = function() {
    return Object.setPrototypeOf(new import_obsidian.Component(), new.target.prototype);
  };
  derived.prototype = base.prototype;
  return Object.setPrototypeOf(derived, base);
}
var spawnLeafView = (plugin, initiatingEl, leaf, onShowCallback) => {
  let parent = plugin.app.workspace.activeLeaf;
  if (!parent)
    parent = leaf;
  if (!initiatingEl)
    initiatingEl = parent == null ? void 0 : parent.containerEl;
  const hoverPopover = new EmbeddedView(parent, initiatingEl, plugin, void 0, onShowCallback);
  return [hoverPopover.attachLeaf(), hoverPopover];
};
var _a, _b, _c, _d;
var EmbeddedView = class extends nosuper(import_obsidian.HoverPopover) {
  constructor(parent, targetEl, plugin, waitTime, onShowCallback) {
    super();
    this.targetEl = targetEl;
    this.plugin = plugin;
    this.onShowCallback = onShowCallback;
    this.abortController = this.addChild(new import_obsidian.Component());
    this.detaching = false;
    this.opening = false;
    this.rootSplit = new import_obsidian.WorkspaceSplit(this.plugin.app.workspace, "vertical");
    this.isPinned = true;
    this.oldPopover = (_a = this.parent) == null ? void 0 : _a.hoverPopover;
    this.document = (_d = (_c = (_b = this.targetEl) == null ? void 0 : _b.ownerDocument) != null ? _c : window.activeDocument) != null ? _d : window.document;
    this.id = genId(8);
    this.hoverEl = this.document.defaultView.createDiv({
      cls: "fs-block fs-leaf-view",
      attr: { id: "fs-" + this.id }
    });
    if (waitTime === void 0) {
      waitTime = 300;
    }
    this.onTarget = true;
    this.parent = parent;
    this.waitTime = waitTime;
    this.state = import_obsidian.PopoverState.Showing;
    const { hoverEl } = this;
    this.abortController.load();
    this.show();
    this.onShow();
    this.setActive = this._setActive.bind(this);
    popovers.set(this.hoverEl, this);
    this.hoverEl.addClass("fs-block");
    this.containerEl = this.hoverEl.createDiv("fs-content");
    this.buildWindowControls();
    this.setInitialDimensions();
  }
  static activeWindows(plugin) {
    const windows = [window];
    const { floatingSplit } = plugin.app.workspace;
    if (floatingSplit) {
      for (const split of floatingSplit.children) {
        if (split.win)
          windows.push(split.win);
      }
    }
    return windows;
  }
  static containerForDocument(doc, plugin) {
    if (doc !== document && plugin.app.workspace.floatingSplit)
      for (const container of plugin.app.workspace.floatingSplit.children) {
        if (container.doc === doc)
          return container;
      }
    return plugin.app.workspace.rootSplit;
  }
  static activePopovers(plugin) {
    return this.activeWindows(plugin).flatMap(this.popoversForWindow);
  }
  static popoversForWindow(win) {
    var _a2, _b2;
    return Array.prototype.slice.call((_b2 = (_a2 = win == null ? void 0 : win.document) == null ? void 0 : _a2.body.querySelectorAll(".fs-leaf-view")) != null ? _b2 : []).map((el) => popovers.get(el)).filter((he) => he);
  }
  static forLeaf(leaf) {
    const el = leaf && document.body.matchParent.call(leaf.containerEl, ".fs-leaf-view");
    return el ? popovers.get(el) : void 0;
  }
  static iteratePopoverLeaves(ws, cb, plugin) {
    for (const popover of this.activePopovers(plugin)) {
      if (popover.rootSplit && ws.iterateLeaves(cb, popover.rootSplit))
        return true;
    }
    return false;
  }
  _setActive(evt) {
    evt.preventDefault();
    evt.stopPropagation();
    this.plugin.app.workspace.setActiveLeaf(this.leaves()[0], { focus: true });
  }
  getDefaultMode() {
    return "source";
  }
  updateLeaves() {
    if (this.onTarget && this.targetEl && !this.document.contains(this.targetEl)) {
      this.onTarget = false;
      this.transition();
    }
    let leafCount = 0;
    this.plugin.app.workspace.iterateLeaves((leaf) => {
      leafCount++;
    }, this.rootSplit);
    if (leafCount === 0) {
      this.hide();
    }
    this.hoverEl.setAttribute("data-leaf-count", leafCount.toString());
  }
  leaves() {
    const leaves = [];
    this.plugin.app.workspace.iterateLeaves((leaf) => {
      leaves.push(leaf);
    }, this.rootSplit);
    return leaves;
  }
  setInitialDimensions() {
    this.hoverEl.style.height = "auto";
    this.hoverEl.style.width = "100%";
  }
  transition() {
    if (this.shouldShow()) {
      if (this.state === import_obsidian.PopoverState.Hiding) {
        this.state = import_obsidian.PopoverState.Shown;
        window.clearTimeout(this.timer);
      }
    } else {
      if (this.state === import_obsidian.PopoverState.Showing) {
        this.hide();
      } else {
        if (this.state === import_obsidian.PopoverState.Shown) {
          this.state = import_obsidian.PopoverState.Hiding;
          this.timer = window.setTimeout(() => {
            if (this.shouldShow()) {
              this.transition();
            } else {
              this.hide();
            }
          }, this.waitTime);
        }
      }
    }
  }
  buildWindowControls() {
    this.titleEl = this.document.defaultView.createDiv("popover-titlebar");
    this.titleEl.createDiv("popover-title");
    this.containerEl.prepend(this.titleEl);
  }
  attachLeaf() {
    this.rootSplit.getRoot = () => this.plugin.app.workspace[this.document === document ? "rootSplit" : "floatingSplit"];
    this.rootSplit.getContainer = () => EmbeddedView.containerForDocument(this.document, this.plugin);
    this.titleEl.insertAdjacentElement("afterend", this.rootSplit.containerEl);
    const leaf = this.plugin.app.workspace.createLeafInParent(this.rootSplit, 0);
    this.updateLeaves();
    return leaf;
  }
  onload() {
    super.onload();
    this.registerEvent(this.plugin.app.workspace.on("layout-change", this.updateLeaves, this));
    this.registerEvent(this.plugin.app.workspace.on("layout-change", () => {
      this.rootSplit.children.forEach((item, index) => {
        if (item instanceof import_obsidian.WorkspaceTabs) {
          this.rootSplit.replaceChild(index, item.children[0]);
        }
      });
    }));
  }
  onShow() {
    var _a2, _b2;
    const closeDelay = 600;
    setTimeout(() => this.waitTime = closeDelay, closeDelay);
    (_a2 = this.oldPopover) == null ? void 0 : _a2.hide();
    this.oldPopover = null;
    this.hoverEl.toggleClass("is-new", true);
    this.document.body.addEventListener("click", () => {
      this.hoverEl.toggleClass("is-new", false);
    }, { once: true, capture: true });
    if (this.parent) {
      this.parent.hoverPopover = this;
    }
    const viewHeaderEl = this.hoverEl.querySelector(".view-header");
    viewHeaderEl == null ? void 0 : viewHeaderEl.remove();
    const sizer = this.hoverEl.querySelector(".workspace-leaf");
    if (sizer)
      this.hoverEl.appendChild(sizer);
    const inlineTitle = this.hoverEl.querySelector(".inline-title");
    if (inlineTitle)
      inlineTitle.remove();
    (_b2 = this.onShowCallback) == null ? void 0 : _b2.call(this);
    this.onShowCallback = void 0;
  }
  detect(el) {
    const { targetEl } = this;
    if (targetEl) {
      this.onTarget = el === targetEl || targetEl.contains(el);
    }
  }
  shouldShow() {
    return this.shouldShowSelf() || this.shouldShowChild();
  }
  shouldShowChild() {
    return EmbeddedView.activePopovers(this.plugin).some((popover) => {
      if (popover !== this && popover.targetEl && this.hoverEl.contains(popover.targetEl)) {
        return popover.shouldShow();
      }
      return false;
    });
  }
  shouldShowSelf() {
    return !this.detaching && !!(this.onTarget || this.state == import_obsidian.PopoverState.Shown || this.document.querySelector(`body>.modal-container, body > #he${this.id} ~ .menu, body > #he${this.id} ~ .suggestion-container`));
  }
  show() {
    this.state = import_obsidian.PopoverState.Shown;
    this.timer = 0;
    this.targetEl.appendChild(this.hoverEl);
    this.onShow();
    this.plugin.app.workspace.onLayoutChange();
    this.load();
    if (this.hoverEl.dataset.imgHeight && this.hoverEl.dataset.imgWidth) {
      this.hoverEl.style.height = parseFloat(this.hoverEl.dataset.imgHeight) + this.titleEl.offsetHeight + "px";
      this.hoverEl.style.width = parseFloat(this.hoverEl.dataset.imgWidth) + "px";
    }
  }
  onHide() {
    var _a2;
    this.oldPopover = null;
    if (((_a2 = this.parent) == null ? void 0 : _a2.hoverPopover) === this) {
      this.parent.hoverPopover = null;
    }
  }
  hide() {
    var _a2;
    this.onTarget = false;
    this.detaching = true;
    if (this.timer) {
      window.clearTimeout(this.timer);
      this.timer = 0;
    }
    this.hoverEl.hide();
    if (this.opening)
      return;
    const leaves = this.leaves();
    if (leaves.length) {
      this.targetEl.empty();
    } else {
      this.parent = null;
      (_a2 = this.abortController) == null ? void 0 : _a2.unload();
      this.abortController = void 0;
      return this.nativeHide();
    }
  }
  nativeHide() {
    var _a2;
    const { hoverEl, targetEl } = this;
    this.state = import_obsidian.PopoverState.Hidden;
    hoverEl.detach();
    if (targetEl) {
      const parent = targetEl.matchParent(".fs-leaf-view");
      if (parent)
        (_a2 = popovers.get(parent)) == null ? void 0 : _a2.transition();
    }
    this.onHide();
    this.unload();
  }
  resolveLink(linkText, sourcePath) {
    const link = (0, import_obsidian.parseLinktext)(linkText);
    const tFile = link ? this.plugin.app.metadataCache.getFirstLinkpathDest(link.path, sourcePath) : null;
    return tFile;
  }
  async openLink(linkText, sourcePath, eState, createInLeaf) {
    var _a2, _b2, _c2;
    let file = this.resolveLink(linkText, sourcePath);
    const link = (0, import_obsidian.parseLinktext)(linkText);
    if (!file && createInLeaf) {
      const folder = this.plugin.app.fileManager.getNewFileParent(sourcePath);
      file = await this.plugin.app.fileManager.createNewMarkdownFile(folder, link.path);
    }
    if (!file) {
      return;
    }
    const { viewRegistry } = this.plugin.app;
    const viewType = viewRegistry.typeByExtension[file.extension];
    if (!viewType || !viewRegistry.viewByType[viewType]) {
      return;
    }
    eState = Object.assign(this.buildEphemeralState(file, link), eState);
    const parentMode = this.getDefaultMode();
    const state = this.buildState(parentMode, eState);
    const leaf = await this.openFile(file, state, createInLeaf);
    const leafViewType = (_a2 = leaf == null ? void 0 : leaf.view) == null ? void 0 : _a2.getViewType();
    if (leafViewType === "image") {
      if (((_b2 = this.parent) == null ? void 0 : _b2.hasOwnProperty("editorEl")) && this.parent.editorEl.hasClass("is-live-preview")) {
        this.waitTime = 3e3;
      }
      const img = leaf.view.contentEl.querySelector("img");
      this.hoverEl.dataset.imgHeight = String(img.naturalHeight);
      this.hoverEl.dataset.imgWidth = String(img.naturalWidth);
      this.hoverEl.dataset.imgRatio = String(img.naturalWidth / img.naturalHeight);
    } else if (leafViewType === "pdf") {
      this.hoverEl.style.height = "800px";
      this.hoverEl.style.width = "600px";
    }
    if (((_c2 = state.state) == null ? void 0 : _c2.mode) === "source") {
      this.whenShown(() => {
        var _a3, _b3, _c3, _d2;
        if ((0, import_obsidian.requireApiVersion)("1.0"))
          (_c3 = (_b3 = (_a3 = leaf == null ? void 0 : leaf.view) == null ? void 0 : _a3.editMode) == null ? void 0 : _b3.reinit) == null ? void 0 : _c3.call(_b3);
        (_d2 = leaf == null ? void 0 : leaf.view) == null ? void 0 : _d2.setEphemeralState(state.eState);
      });
    }
  }
  whenShown(callback) {
    if (this.detaching)
      return;
    const existingCallback = this.onShowCallback;
    this.onShowCallback = () => {
      if (this.detaching)
        return;
      callback();
      if (typeof existingCallback === "function")
        existingCallback();
    };
    if (this.state === import_obsidian.PopoverState.Shown) {
      this.onShowCallback();
      this.onShowCallback = void 0;
    }
  }
  async openFile(file, openState, useLeaf) {
    if (this.detaching)
      return;
    const leaf = useLeaf != null ? useLeaf : this.attachLeaf();
    this.opening = true;
    try {
      await leaf.openFile(file, openState);
    } catch (e) {
      console.error(e);
    } finally {
      this.opening = false;
      if (this.detaching)
        this.hide();
    }
    this.plugin.app.workspace.setActiveLeaf(leaf);
    return leaf;
  }
  buildState(parentMode, eState) {
    return {
      active: false,
      state: { mode: "source" },
      eState
    };
  }
  buildEphemeralState(file, link) {
    const cache = this.plugin.app.metadataCache.getFileCache(file);
    const subpath = cache ? (0, import_obsidian.resolveSubpath)(cache, (link == null ? void 0 : link.subpath) || "") : void 0;
    const eState = { subpath: link == null ? void 0 : link.subpath };
    if (subpath) {
      eState.line = subpath.start.line;
      eState.startLoc = subpath.start;
      eState.endLoc = subpath.end || void 0;
    }
    return eState;
  }
};

// node_modules/.pnpm/monkey-around@2.3.0/node_modules/monkey-around/mjs/index.js
function around(obj, factories) {
  const removers = Object.keys(factories).map((key) => around1(obj, key, factories[key]));
  return removers.length === 1 ? removers[0] : function() {
    removers.forEach((r) => r());
  };
}
function around1(obj, method, createWrapper) {
  const original = obj[method], hadOwn = obj.hasOwnProperty(method);
  let current = createWrapper(original);
  if (original)
    Object.setPrototypeOf(current, original);
  Object.setPrototypeOf(wrapper, current);
  obj[method] = wrapper;
  return remove;
  function wrapper(...args) {
    if (current === original && obj[method] === wrapper)
      remove();
    return current.apply(this, args);
  }
  function remove() {
    if (obj[method] === wrapper) {
      if (hadOwn)
        obj[method] = original;
      else
        delete obj[method];
    }
    if (current === original)
      return;
    current = original;
    Object.setPrototypeOf(wrapper, original || Function);
  }
}

// src/floatSearchIndex.ts
var import_obsidian3 = require("obsidian");
var DEFAULT_SETTINGS = {
  searchViewState: {
    collapseAll: false,
    explainSearch: false,
    extraContext: false,
    matchingCase: false,
    query: "",
    sortOrder: "alphabetical"
  },
  showFilePath: false,
  showInstructions: true,
  defaultViewType: "modal",
  cmdkTriggerKey: "Shift",
  cmdkDoubleTapInterval: 300
};
var allViews = [
  {
    type: "modal",
    icon: "square-equal"
  },
  {
    type: "sidebar",
    icon: "panel-left-inactive"
  },
  {
    type: "split",
    icon: "split-square-horizontal"
  },
  {
    type: "tab",
    icon: "panel-top"
  },
  {
    type: "window",
    icon: "app-window"
  }
];
var initSearchViewWithLeaf = async (app, type, state) => {
  const leaf = type === "sidebar" ? app.workspace.getLeftLeaf(false) : app.workspace.getLeaf(type);
  leaf == null ? void 0 : leaf.setPinned(type !== "sidebar");
  await (leaf == null ? void 0 : leaf.setViewState({
    type: "search",
    active: true,
    state: {
      ...DEFAULT_SETTINGS.searchViewState,
      ...state,
      triggerBySelf: true
    }
  }));
  setTimeout(() => {
    var _a2;
    const inputEl = (_a2 = leaf == null ? void 0 : leaf.containerEl.getElementsByTagName("input")) == null ? void 0 : _a2[0];
    inputEl == null ? void 0 : inputEl.focus();
  }, 0);
};
var FloatSearchPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.allLoaded = false;
    this.queryLoaded = false;
    this.patchedDomChildren = false;
    this.applySettingsUpdate = (0, import_obsidian3.debounce)(async () => {
      var _a2;
      if (!this.allLoaded) {
        this.allLoaded = true;
        return;
      }
      this.settings.searchViewState = {
        ...DEFAULT_SETTINGS.searchViewState,
        ...this.settings.searchViewState,
        query: ((_a2 = this.state) == null ? void 0 : _a2.query) || ""
      };
      await this.saveSettings();
    }, 1e3);
    this.applyStateUpdate = (0, import_obsidian3.debounce)(() => {
      this.state = {
        ...DEFAULT_SETTINGS.searchViewState,
        ...this.state,
        query: ""
      };
    }, 3e4);
  }
  async onload() {
    await this.loadSettings();
    this.app.workspace.onLayoutReady(() => {
      this.initState();
      this.registerIcons();
      this.patchWorkspace();
      this.patchWorkspaceLeaf();
      this.patchSearchView();
      this.patchVchildren();
      this.patchDragManager();
      this.registerDoubleKeyHandler();
    });
    this.registerObsidianURIHandler();
    this.registerObsidianCommands();
    this.registerEditorMenuHandler();
    this.registerContextMenuHandler();
    this.addRibbonIcon("search", `Search obsidian in ${this.settings.defaultViewType} view`, () => {
      if (this.settings.defaultViewType === "modal") {
        this.initModal(this.state, true, true);
      } else {
        initSearchViewWithLeaf(this.app, this.settings.defaultViewType, {
          ...this.state,
          query: ""
        });
      }
    });
    this.updateFilePathVisibility();
    this.addSettingTab(new FloatSearchSettingTab(this.app, this));
  }
  onunload() {
    var _a2;
    (_a2 = this.modal) == null ? void 0 : _a2.close();
  }
  registerDoubleKeyHandler() {
    let lastKeyUp = 0;
    let keyOnly = true;
    this.registerDomEvent(document, "keydown", (e) => {
      const triggerKey = this.settings.cmdkTriggerKey;
      if (triggerKey === "none" || e.key !== triggerKey) {
        keyOnly = false;
      }
    });
    this.registerDomEvent(document, "keyup", (e) => {
      const triggerKey = this.settings.cmdkTriggerKey;
      if (triggerKey === "none")
        return;
      if (e.key === triggerKey) {
        const now = Date.now();
        if (keyOnly && now - lastKeyUp < this.settings.cmdkDoubleTapInterval && !document.querySelector(".float-search-cmdk-container")) {
          lastKeyUp = 0;
          this.openCmdkModal();
        } else {
          lastKeyUp = now;
          keyOnly = true;
        }
      }
    });
  }
  openCmdkModal() {
    if (this.cmdkModal) {
      this.cmdkModal.close();
    }
    this.cmdkModal = new FloatSearchCmdkModal(this);
    this.cmdkModal.open();
  }
  updateFilePathVisibility() {
    const { showFilePath } = this.settings;
    document.body.toggleClass("show-file-path", showFilePath);
  }
  changeFilePathVisibility() {
    this.settings.showFilePath = !this.settings.showFilePath;
    this.updateFilePathVisibility();
    this.applySettingsUpdate();
  }
  initState() {
    this.state = {
      ...DEFAULT_SETTINGS.searchViewState,
      ...this.settings.searchViewState
    };
  }
  initModal(state, stateSave = false, clearQuery = false) {
    if (this.modal) {
      this.modal.close();
    }
    this.modal = new FloatSearchModal((state2) => {
      this.state = {
        ...DEFAULT_SETTINGS.searchViewState,
        ...state2
      };
      if (stateSave)
        this.applyStateUpdate();
      this.settings.searchViewState = this.state;
      this.applySettingsUpdate();
    }, this, { ...state, query: clearQuery ? "" : state.query });
    this.modal.open();
  }
  patchWorkspace() {
    let layoutChanging = false;
    const self = this;
    const uninstaller = around(import_obsidian2.Workspace.prototype, {
      getLeaf: (next) => function(...args) {
        const activeLeaf = this.activeLeaf;
        if (activeLeaf) {
          const fsCtnEl = activeLeaf.parent.containerEl.parentElement;
          if (fsCtnEl == null ? void 0 : fsCtnEl.hasClass("fs-content")) {
            if (activeLeaf.view.getViewType() === "markdown") {
              return activeLeaf;
            }
            const newLeaf = self.app.workspace.getMostRecentLeaf();
            if (newLeaf) {
              this.setActiveLeaf(newLeaf);
            }
          }
          return next.call(this, ...args);
        }
        return next.call(this, ...args);
      },
      changeLayout(old) {
        return async function(workspace) {
          layoutChanging = true;
          try {
            await old.call(this, workspace);
          } finally {
            layoutChanging = false;
          }
        };
      },
      iterateLeaves(old) {
        return function(arg1, arg2) {
          if (old.call(this, arg1, arg2))
            return true;
          const cb = typeof arg1 === "function" ? arg1 : arg2;
          const parent = typeof arg1 === "function" ? arg2 : arg1;
          if (!parent)
            return false;
          if (layoutChanging)
            return false;
          if (!(0, import_obsidian2.requireApiVersion)("0.15.0")) {
            if (parent === self.app.workspace.rootSplit || import_obsidian2.WorkspaceContainer && parent instanceof import_obsidian2.WorkspaceContainer) {
              for (const popover of EmbeddedView.popoversForWindow(parent.win)) {
                if (old.call(this, cb, popover.rootSplit))
                  return false;
              }
            }
          }
          return false;
        };
      },
      setActiveLeaf(old) {
        return function(leaf, params) {
          if (isEmebeddedLeaf(leaf)) {
            old.call(this, leaf, params);
            leaf.activeTime = 17e11;
          }
          return old.call(this, leaf, params);
        };
      },
      pushUndoHistory(old) {
        return function(leaf, id, ...args) {
          const viewState = leaf.getViewState();
          if (viewState.type === "search") {
            return;
          }
          return old.call(this, leaf, id, ...args);
        };
      }
    });
    this.register(uninstaller);
  }
  patchWorkspaceLeaf() {
    this.register(around(import_obsidian2.WorkspaceLeaf.prototype, {
      getRoot(old) {
        return function() {
          const top = old.call(this);
          return (top == null ? void 0 : top.getRoot) === this.getRoot ? top : top == null ? void 0 : top.getRoot();
        };
      },
      setPinned(old) {
        return function(pinned) {
          old.call(this, pinned);
          if (isEmebeddedLeaf(this) && !pinned)
            this.setPinned(true);
        };
      },
      openFile(old) {
        return function(file, openState) {
          if (isEmebeddedLeaf(this)) {
            setTimeout(around(import_obsidian2.Workspace.prototype, {
              recordMostRecentOpenedFile(old2) {
                return function(_file) {
                  if (_file !== file) {
                    return old2.call(this, _file);
                  }
                };
              }
            }), 1);
            const recentFiles = this.app.plugins.plugins["recent-files-obsidian"];
            if (recentFiles) {
              setTimeout(around(recentFiles, {
                shouldAddFile(old2) {
                  return function(_file) {
                    return _file !== file && old2.call(this, _file);
                  };
                }
              }), 1);
            }
          }
          const view = old.call(this, file, openState);
          setTimeout(() => {
            const fsCtnEl = this.parent.containerEl.parentElement;
            if (!(fsCtnEl == null ? void 0 : fsCtnEl.classList.contains("fs-content")))
              return;
            if (file.extension != "canvas")
              return;
            const canvas = this.view.canvas;
            setTimeout(() => {
              var _a2, _b2;
              if (canvas && ((_a2 = openState == null ? void 0 : openState.eState) == null ? void 0 : _a2.match)) {
                let node = (_b2 = canvas.data.nodes) == null ? void 0 : _b2.find((e) => {
                  var _a3, _b3;
                  return e.text === ((_b3 = (_a3 = openState == null ? void 0 : openState.eState) == null ? void 0 : _a3.match) == null ? void 0 : _b3.content);
                });
                if (node) {
                  node = canvas.nodes.get(node.id);
                  canvas.selectOnly(node);
                  canvas.zoomToSelection();
                }
              }
            }, 20);
          }, 1);
          return view;
        };
      }
    }));
  }
  patchSearchView() {
    const checkCurrentViewType = (leaf) => {
      var _a2;
      const isModal = document.querySelector(".float-search-modal") !== null;
      const currentLeafRoot = leaf.getRoot();
      if ((currentLeafRoot == null ? void 0 : currentLeafRoot.side) && ((currentLeafRoot == null ? void 0 : currentLeafRoot.side) === "left" || (currentLeafRoot == null ? void 0 : currentLeafRoot.side) === "right"))
        return "sidebar";
      if (((_a2 = leaf.getContainer()) == null ? void 0 : _a2.type) === "window")
        return "window";
      return isModal ? "modal" : "split";
    };
    const initViewMenu = (menu, current, originLeaf) => {
      menu.dom.toggleClass("float-search-view-menu", true);
      let availableViews = allViews.filter((view) => {
        if (current === "split") {
          return view.type !== "tab";
        } else {
          return view.type !== current;
        }
      });
      for (const view of availableViews) {
        menu.addItem((item) => {
          item.setTitle(`${view.type} view`).setIcon(`${view.icon}`).onClick(async () => {
            if (view.type === "modal") {
              originLeaf == null ? void 0 : originLeaf.detach();
              setTimeout(() => {
                this.initModal(this.state, true, false);
              }, 10);
            } else if (view.type === "sidebar") {
              await initSearchViewWithLeaf(this.app, view.type, this.state);
            } else {
              if (current === "window") {
                originLeaf == null ? void 0 : originLeaf.detach();
                setTimeout(async () => {
                  await initSearchViewWithLeaf(this.app, view.type, this.state);
                }, 10);
              } else {
                await initSearchViewWithLeaf(this.app, view.type, this.state);
              }
            }
            if (current === "modal") {
              this.modal.close();
            } else {
              originLeaf == null ? void 0 : originLeaf.detach();
            }
          });
        });
      }
      return menu;
    };
    const patchSearch = async () => {
      var _a2;
      const searchLeaf = this.app.workspace.getLeavesOfType("search")[0];
      if (!searchLeaf)
        return false;
      if ((0, import_obsidian2.requireApiVersion)("1.7.3") && searchLeaf.isDeferred) {
        await searchLeaf.loadIfDeferred();
      }
      const searchView = searchLeaf == null ? void 0 : searchLeaf.view;
      const self = this;
      if (!searchView)
        return false;
      const searchViewConstructor = searchView.constructor;
      this.register(around(searchViewConstructor.prototype, {
        onOpen(old) {
          return function() {
            old.call(this);
            const viewSwitchEl = createDiv({
              cls: "float-search-view-switch"
            });
            const targetEl = this.filterSectionToggleEl;
            const viewSwitchButton = new import_obsidian2.ExtraButtonComponent(viewSwitchEl);
            viewSwitchButton.setIcon("layout-template").setTooltip("Switch to File View");
            viewSwitchButton.onClick(() => {
              const currentType = checkCurrentViewType(this.leaf);
              const layoutMenu = initViewMenu(new import_obsidian2.Menu(), currentType, this.leaf);
              const viewSwitchButtonPos = viewSwitchEl.getBoundingClientRect();
              layoutMenu.showAtPosition({
                x: viewSwitchButtonPos.x,
                y: viewSwitchButtonPos.y + 30
              });
            });
            targetEl.parentElement.insertBefore(viewSwitchEl, targetEl);
            if (!this.hidePathToggle) {
              this.hidePathToggle = new import_obsidian2.Setting(this.searchParamsContainerEl).setName("Show file path").addToggle((toggle) => {
                toggle.toggleEl.toggleClass("mod-small", true);
                toggle.setValue(self.settings.showFilePath).onChange(async (value) => {
                  self.settings.showFilePath = !value;
                  self.changeFilePathVisibility();
                  self.applySettingsUpdate();
                });
              });
            }
            if (!this.showInstructionsToggle) {
              this.showInstructionsToggle = new import_obsidian2.Setting(this.searchParamsContainerEl).setName("Show instructions").addToggle((toggle) => {
                toggle.toggleEl.toggleClass("mod-small", true);
                toggle.setValue(self.settings.showInstructions).onChange(async (value) => {
                  self.settings.showInstructions = value;
                  self.applySettingsUpdate();
                });
              });
            }
            if (!this.defaultViewTypeDropdown) {
              this.defaultViewTypeDropdown = new import_obsidian2.Setting(this.searchParamsContainerEl).setName("Default view type").addDropdown((dropdown) => {
                dropdown.addOptions({
                  modal: "Modal",
                  split: "Split",
                  tab: "Tab",
                  window: "Window",
                  sidebar: "Sidebar"
                });
                dropdown.setValue(self.settings.defaultViewType);
                dropdown.onChange((value) => {
                  self.settings.defaultViewType = value;
                  self.applySettingsUpdate();
                });
              });
            }
          };
        },
        setExplainSearch(old) {
          return function(value) {
            old.call(this, value);
            if (self.app.workspace.layoutReady) {
              self.settings.searchViewState.explainSearch = value;
              self.applySettingsUpdate();
            }
          };
        },
        setCollapseAll(old) {
          return function(value) {
            old.call(this, value);
            if (self.app.workspace.layoutReady) {
              self.settings.searchViewState.collapseAll = value;
              self.applySettingsUpdate();
            }
          };
        },
        setExtraContext(old) {
          return function(value) {
            old.call(this, value);
            if (self.app.workspace.layoutReady) {
              self.settings.searchViewState.extraContext = value;
              self.applySettingsUpdate();
            }
          };
        },
        setMatchingCase(old) {
          return function(value) {
            old.call(this, value);
            if (self.app.workspace.layoutReady) {
              self.settings.searchViewState.matchingCase = value;
              self.applySettingsUpdate();
            }
          };
        },
        setSortOrder(old) {
          return function(value) {
            old.call(this, value);
            if (self.app.workspace.layoutReady) {
              self.settings.searchViewState.sortOrder = value;
              self.applySettingsUpdate();
            }
          };
        },
        setQuery(old) {
          return function(value) {
            old.call(this, value);
            if (self.app.workspace.layoutReady) {
              self.settings.searchViewState.query = value;
              self.applySettingsUpdate();
            }
          };
        },
        setState(old) {
          return function(state, eState) {
            if (typeof state.query === "string" && !(state == null ? void 0 : state.triggerBySelf)) {
              if (self.queryLoaded) {
                if (self.settings.defaultViewType === "modal") {
                  self.initModal({
                    ...state,
                    query: state.query,
                    current: false,
                    triggerBySelf: true
                  }, true, false);
                } else {
                  initSearchViewWithLeaf(self.app, self.settings.defaultViewType, {
                    ...state,
                    query: state.query,
                    current: false,
                    triggerBySelf: true
                  });
                }
                return;
              }
              self.queryLoaded = true;
            }
            old.call(this, state, eState);
          };
        }
      }));
      (_a2 = searchView.leaf) == null ? void 0 : _a2.rebuildView();
      return true;
    };
    this.app.workspace.onLayoutReady(async () => {
      if (!await patchSearch()) {
        const evt = this.app.workspace.on("layout-change", async () => {
          await patchSearch() && this.app.workspace.offref(evt);
        });
        this.registerEvent(evt);
      }
    });
  }
  patchVchildren() {
    const patchSearchDom = () => {
      var _a2;
      const searchView = (_a2 = this.app.workspace.getLeavesOfType("search")[0]) == null ? void 0 : _a2.view;
      if (!searchView)
        return false;
      const dom = searchView.dom.constructor;
      const self = this;
      this.register(around(dom.prototype, {
        stopLoader(old) {
          return function() {
            var _a3, _b2;
            old.call(this);
            (_b2 = (_a3 = this == null ? void 0 : this.vChildren) == null ? void 0 : _a3.children) == null ? void 0 : _b2.forEach((child) => {
              var _a4;
              if ((child == null ? void 0 : child.file) && !(child == null ? void 0 : child.pathEl)) {
                const path = ((_a4 = child == null ? void 0 : child.file.parent) == null ? void 0 : _a4.path) || "/";
                const pathEl = createDiv({
                  cls: "search-result-file-path"
                });
                const pathIconEl = pathEl.createDiv({
                  cls: "search-result-file-path-icon"
                });
                (0, import_obsidian2.setIcon)(pathIconEl, "folder");
                const pathTextEl = pathEl.createDiv({
                  cls: "search-result-file-path-text",
                  text: path
                });
                child.pathEl = pathEl;
                const titleEl = child.containerEl.find(".search-result-file-title");
                titleEl.prepend(pathEl);
              }
            });
          };
        }
      }));
      return true;
    };
    this.app.workspace.onLayoutReady(() => {
      if (!patchSearchDom()) {
        const evt = this.app.workspace.on("layout-change", () => {
          patchSearchDom() && this.app.workspace.offref(evt);
        });
        this.registerEvent(evt);
      }
    });
  }
  patchDragManager() {
    const manager = this.app.dragManager;
    if (!manager)
      return;
    const self = this;
    this.register(around(manager.constructor.prototype, {
      dragFile(old) {
        return function(e, a) {
          const result = old.call(this, e, a);
          setTimeout(() => {
            var _a2;
            (_a2 = self == null ? void 0 : self.modal) == null ? void 0 : _a2.close();
          }, 10);
          return result;
        };
      }
    }));
  }
  registerObsidianURIHandler() {
    this.registerObsidianProtocolHandler("fs", async (path) => {
      const viewType = path.viewType || "modal";
      const query = path.query || "";
      if (viewType === "modal") {
        this.initModal({
          ...this.state,
          query,
          current: false
        }, true, false);
      } else {
        await initSearchViewWithLeaf(this.app, viewType, {
          ...this.state,
          query,
          current: false
        });
      }
    });
  }
  createCommand(options) {
    if (options.global) {
      this.addCommand({
        id: options.id,
        name: options.name,
        callback: () => {
          const query = options.queryBuilder();
          const viewType = this.settings.defaultViewType;
          if (viewType === "modal") {
            this.initModal({ ...this.state, query, current: true }, true, false);
          } else {
            initSearchViewWithLeaf(this.app, viewType, {
              ...this.state,
              query,
              current: true
            });
          }
        }
      });
    } else {
      this.addCommand({
        id: options.id,
        name: options.name,
        checkCallback: (checking) => {
          const activeLeaf = this.app.workspace.activeLeaf;
          if (!activeLeaf)
            return;
          const viewType = activeLeaf.view.getViewType();
          if (viewType === "markdown" || viewType === "canvas") {
            if (!checking) {
              const currentFile = activeLeaf.view.file;
              const query = options.queryBuilder(currentFile);
              const viewType2 = this.settings.defaultViewType;
              if (viewType2 === "modal") {
                this.initModal({ ...this.state, query, current: true }, true, false);
              } else {
                initSearchViewWithLeaf(this.app, viewType2, {
                  ...this.state,
                  query,
                  current: true
                });
              }
            }
            return true;
          }
        }
      });
    }
  }
  registerObsidianCommands() {
    this.addCommand({
      id: "show-or-hide-file-path",
      name: "Show/hide file path",
      callback: () => {
        this.changeFilePathVisibility();
      }
    });
    this.addCommand({
      id: "search-obsidian-globally",
      name: "Search obsidian globally",
      callback: () => this.initModal({ ...this.state, query: "", current: false }, false, true)
    });
    this.addCommand({
      id: "search-obsidian-globally-state",
      name: "Search Obsidian Globally (With Last State)",
      callback: () => this.initModal({ ...this.state, query: this.state.query, current: false }, true, false)
    });
    this.createCommand({
      id: "search-in-backlink",
      name: "Search in backlink Of current file",
      queryBuilder: (file) => {
        if (!file)
          return "";
        return " /\\[\\[" + (file.extension === "canvas" ? file.name : file.basename) + "(\\|[^\\]]*)?\\]\\]/";
      },
      global: false
    });
    this.createCommand({
      id: "search-in-current-file",
      name: "Search in current file",
      queryBuilder: (file) => {
        if (!file)
          return "";
        return ` path:"${file.path}"`;
      },
      global: false
    });
    this.registerSearchOperatorCommands();
    for (const type of ["split", "tab", "window"]) {
      this.addCommand({
        id: `open-search-view-${type}`,
        name: `Open search view (${type})`,
        callback: async () => {
          const existingLeaf = this.app.workspace.getLeavesOfType("search");
          switch (type) {
            case "window":
              const isExistingWindowLeaf = existingLeaf.find((leaf) => leaf.parentSplit.parent.type === "window");
              if (isExistingWindowLeaf) {
                this.app.workspace.revealLeaf(isExistingWindowLeaf);
                return;
              }
              await initSearchViewWithLeaf(this.app, type, {
                ...this.state,
                triggerBySelf: true
              });
              break;
            case "tab":
            case "split":
              const isExistingLeaf = existingLeaf.find((leaf) => !leaf.parentSplit.parent.side);
              if (isExistingLeaf) {
                this.app.workspace.revealLeaf(isExistingLeaf);
                isExistingLeaf.setViewState({
                  type: "search",
                  active: true,
                  state: {
                    ...this.state,
                    triggerBySelf: true
                  }
                });
                return;
              }
              await initSearchViewWithLeaf(this.app, type, {
                ...this.state,
                triggerBySelf: true
              });
              break;
          }
        }
      });
    }
  }
  registerSearchOperatorCommands() {
    const searchOperators = [
      {
        id: "search-file-operator",
        name: "Search: file: (Find text in filename)",
        query: "file:"
      },
      {
        id: "search-path-operator",
        name: "Search: path: (Find text in file path)",
        query: "path:"
      },
      {
        id: "search-content-operator",
        name: "Search: content: (Find text in file content)",
        query: "content:"
      },
      {
        id: "search-match-case-operator",
        name: "Search: match-case: (Case-sensitive match)",
        query: "match-case:"
      },
      {
        id: "search-ignore-case-operator",
        name: "Search: ignore-case: (Case-insensitive match)",
        query: "ignore-case:"
      },
      {
        id: "search-tag-operator",
        name: "Search: tag: (Find tag)",
        query: "tag:"
      },
      {
        id: "search-line-operator",
        name: "Search: line: (Find files with matching line)",
        query: "line:"
      },
      {
        id: "search-block-operator",
        name: "Search: block: (Find matches in the same block)",
        query: "block:"
      },
      {
        id: "search-section-operator",
        name: "Search: section: (Find matches in the same section)",
        query: "section:"
      },
      {
        id: "search-task-operator",
        name: "Search: task: (Find matches in a task)",
        query: "task:"
      },
      {
        id: "search-task-todo-operator",
        name: "Search: task-todo: (Find matches in uncompleted tasks)",
        query: "task-todo:"
      },
      {
        id: "search-task-done-operator",
        name: "Search: task-done: (Find matches in completed tasks)",
        query: "task-done:"
      },
      {
        id: "search-property",
        name: "Search: [property] or [property:value]",
        query: "[]"
      }
    ];
    searchOperators.forEach((operator) => {
      this.createCommand({
        id: operator.id,
        name: operator.name,
        queryBuilder: () => operator.query || "",
        global: true
      });
    });
  }
  registerEditorMenuHandler() {
    this.registerEvent(this.app.workspace.on("editor-menu", (menu, editor) => {
      if (!editor) {
        return;
      }
      if (editor.getSelection().length === 0) {
        return;
      }
      const selection = editor.getSelection().trim();
      let searchWord = selection;
      if (selection.length > 8) {
        searchWord = selection.substring(0, 3) + "..." + selection.substring(selection.length - 3, selection.length);
      } else {
        searchWord = selection;
      }
      menu.addItem((item) => {
        item.setTitle('Search "' + searchWord + '" in Float Search').setIcon("search").onClick(() => this.initModal({
          ...this.state,
          query: selection,
          current: false
        }, true, false));
      });
    }));
  }
  registerContextMenuHandler() {
    this.registerEvent(this.app.workspace.on("file-menu", (menu, file, source, leaf) => {
      const popover = leaf ? EmbeddedView.forLeaf(leaf) : void 0;
      if (file instanceof import_obsidian2.TFile && !popover && !leaf) {
        menu.addItem((item) => {
          var _a2, _b2;
          (_b2 = (_a2 = item.setIcon("popup-open").setTitle("Open in Float Preview").onClick(async () => {
            if (this.modal) {
              await this.modal.initFileView(file, void 0);
              return;
            }
            this.initModal({ ...this.state, current: false }, true, true);
            setTimeout(async () => {
              await this.modal.initFileView(file, void 0);
            }, 20);
          })).setSection) == null ? void 0 : _b2.call(_a2, "open");
        });
      }
    }));
  }
  registerIcons() {
    (0, import_obsidian2.addIcon)("panel-left-inactive", `<path style="fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke:currentColor;stroke-opacity:1;stroke-miterlimit:4;" d="M 4.999687 3 L 19.000312 3 C 20.104688 3 21 3.895312 21 4.999687 L 21 19.000312 C 21 20.104688 20.104688 21 19.000312 21 L 4.999687 21 C 3.895312 21 3 20.104688 3 19.000312 L 3 4.999687 C 3 3.895312 3.895312 3 4.999687 3 Z M 4.999687 3 " transform="matrix(4.166667,0,0,4.166667,0,0)"/><path style="fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke:currentColor;stroke-opacity:1;stroke-miterlimit:4;" d="M 9 13.999688 L 9 15 " transform="matrix(4.166667,0,0,4.166667,0,0)"/><path style="fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke:currentColor;stroke-opacity:1;stroke-miterlimit:4;" d="M 9 19.000312 L 9 21 " transform="matrix(4.166667,0,0,4.166667,0,0)"/><path style="fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke:currentColor;stroke-opacity:1;stroke-miterlimit:4;" d="M 9 3 L 9 4.999687 " transform="matrix(4.166667,0,0,4.166667,0,0)"/><path style="fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke:currentColor;stroke-opacity:1;stroke-miterlimit:4;" d="M 9 9 L 9 10.000312 " transform="matrix(4.166667,0,0,4.166667,0,0)"/>`);
    (0, import_obsidian2.addIcon)("app-window", `<path style="fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke:currentColor;stroke-opacity:1;stroke-miterlimit:4;" d="M 4.000312 4.000312 L 19.999688 4.000312 C 21.105 4.000312 22.000312 4.895625 22.000312 6 L 22.000312 18 C 22.000312 19.104375 21.105 19.999688 19.999688 19.999688 L 4.000312 19.999688 C 2.895 19.999688 1.999687 19.104375 1.999687 18 L 1.999687 6 C 1.999687 4.895625 2.895 4.000312 4.000312 4.000312 Z M 4.000312 4.000312 " transform="matrix(4.166667,0,0,4.166667,0,0)"/><path style="fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke:currentColor;stroke-opacity:1;stroke-miterlimit:4;" d="M 10.000312 4.000312 L 10.000312 7.999687 " transform="matrix(4.166667,0,0,4.166667,0,0)"/><path style="fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke:currentColor;stroke-opacity:1;stroke-miterlimit:4;" d="M 1.999687 7.999687 L 22.000312 7.999687 " transform="matrix(4.166667,0,0,4.166667,0,0)"/><path style="fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke:currentColor;stroke-opacity:1;stroke-miterlimit:4;" d="M 6 4.000312 L 6 7.999687 " transform="matrix(4.166667,0,0,4.166667,0,0)"/>`);
    (0, import_obsidian2.addIcon)("panel-top", `<path style="fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke:currentColor;stroke-opacity:1;stroke-miterlimit:4;" d="M 4.999687 3 L 19.000312 3 C 20.104688 3 21 3.895312 21 4.999687 L 21 19.000312 C 21 20.104688 20.104688 21 19.000312 21 L 4.999687 21 C 3.895312 21 3 20.104688 3 19.000312 L 3 4.999687 C 3 3.895312 3.895312 3 4.999687 3 Z M 4.999687 3 " transform="matrix(4.166667,0,0,4.166667,0,0)"/><path style="fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke:currentColor;stroke-opacity:1;stroke-miterlimit:4;" d="M 3 9 L 21 9 " transform="matrix(4.166667,0,0,4.166667,0,0)"/>`);
    (0, import_obsidian2.addIcon)("square-equal", `<path style="fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke:currentColor;stroke-opacity:1;stroke-miterlimit:4;" d="M 4.999687 3 L 19.000312 3 C 20.104688 3 21 3.895312 21 4.999687 L 21 19.000312 C 21 20.104688 20.104688 21 19.000312 21 L 4.999687 21 C 3.895312 21 3 20.104688 3 19.000312 L 3 4.999687 C 3 3.895312 3.895312 3 4.999687 3 Z M 4.999687 3 " transform="matrix(4.166667,0,0,4.166667,0,0)"/><path style="fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke:currentColor;stroke-opacity:1;stroke-miterlimit:4;" d="M 7.000312 10.000312 L 16.999688 10.000312 " transform="matrix(4.166667,0,0,4.166667,0,0)"/><path style="fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke:currentColor;stroke-opacity:1;stroke-miterlimit:4;" d="M 7.000312 13.999688 L 16.999688 13.999688 " transform="matrix(4.166667,0,0,4.166667,0,0)"/>`);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var TRIGGER_KEY_OPTIONS = {
  Shift: "Double Shift",
  Control: "Double Ctrl",
  Alt: "Double Alt",
  Meta: "Double Meta (Cmd/Win)",
  none: "Disabled"
};
var FloatSearchSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Float Search Settings" });
    new import_obsidian2.Setting(containerEl).setName("Quick search trigger").setDesc("Double-tap this key to open the quick search modal (CMDK).").addDropdown((dropdown) => {
      for (const [value, label] of Object.entries(TRIGGER_KEY_OPTIONS)) {
        dropdown.addOption(value, label);
      }
      dropdown.setValue(this.plugin.settings.cmdkTriggerKey);
      dropdown.onChange(async (value) => {
        this.plugin.settings.cmdkTriggerKey = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Double-tap interval (ms)").setDesc("Maximum time between two key presses to trigger quick search. Default: 300ms.").addSlider((slider) => {
      slider.setLimits(150, 600, 50).setValue(this.plugin.settings.cmdkDoubleTapInterval).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.cmdkDoubleTapInterval = value;
        await this.plugin.saveSettings();
      });
    });
  }
};
function createInstructionElement(parentEl, divCls, keyText, text) {
  const divEl = parentEl.createDiv({ cls: divCls });
  const iconEl = divEl.createSpan({
    cls: "float-search-modal-instructions-key"
  });
  const textEl = divEl.createSpan({
    cls: "float-search-modal-instructions-text"
  });
  iconEl.setText(keyText);
  textEl.setText(text);
  return { divEl, iconEl, textEl };
}
var FloatSearchModal = class extends import_obsidian2.Modal {
  constructor(cb, plugin, state, viewType = "search") {
    super(plugin.app);
    this.debouncedAutoPreview = (0, import_obsidian3.debounce)(() => {
      this.autoPreviewFocusedItem();
    }, 150);
    this.plugin = plugin;
    this.cb = cb;
    this.state = state;
    this.viewType = viewType;
  }
  async onOpen() {
    const { contentEl, containerEl, modalEl } = this;
    this.searchCtnEl = contentEl.createDiv({
      cls: "float-search-modal-search-ctn"
    });
    this.instructionsEl = modalEl.createDiv({
      cls: "float-search-modal-instructions"
    });
    this.initInstructions(this.instructionsEl);
    this.initCss(contentEl, modalEl, containerEl);
    await this.initSearchView(this.searchCtnEl);
    this.initInput();
    this.initContent();
  }
  onClose() {
    var _a2, _b2;
    const { contentEl } = this;
    this.cb(this.searchLeaf.view.getState());
    this.searchLeaf.detach();
    (_a2 = this.fileLeaf) == null ? void 0 : _a2.detach();
    this.searchEmbeddedView.unload();
    (_b2 = this.fileEmbeddedView) == null ? void 0 : _b2.unload();
    contentEl.empty();
  }
  initInstructions(instructionsEl) {
    if (!this.plugin.settings.showInstructions) {
      return;
    }
    const navigate = createInstructionElement(instructionsEl, "float-search-modal-instructions-navigate", "\u2191\u2193", "Navigate");
    const collapse = createInstructionElement(instructionsEl, "float-search-modal-instructions-collapse", "Shift+\u2191\u2193", "Collapse/Expand");
    const enter = createInstructionElement(instructionsEl, "float-search-modal-instructions-enter", "\u21B5", "Open in background");
    const altEnter = createInstructionElement(instructionsEl, "float-search-modal-instructions-alt-enter", "Alt+\u21B5", "Open File and Close");
    const ctrlEnter = createInstructionElement(instructionsEl, "float-search-modal-instructions-ctrl-enter", "Ctrl+\u21B5", "Create File When Not Exist");
    const tab = createInstructionElement(instructionsEl, "float-search-modal-instructions-tab", "Tab/Shift+Tab", "Preview/Close Preview");
    const switchView = createInstructionElement(instructionsEl, "float-search-modal-instructions-switch", "Ctrl+G", "Switch Between Search and File View");
    const click = createInstructionElement(instructionsEl, "float-search-modal-instructions-click", "Alt+Click", "Close Modal While In File View");
  }
  initCss(contentEl, modalEl, containerEl) {
    contentEl.classList.add("float-search-modal-content");
    modalEl.classList.add("float-search-modal");
    containerEl.classList.add("float-search-modal-container");
  }
  async initSearchView(contentEl) {
    const [createdLeaf, embeddedView] = spawnLeafView(this.plugin, contentEl);
    this.searchLeaf = createdLeaf;
    this.searchEmbeddedView = embeddedView;
    this.searchLeaf.setPinned(true);
    await this.searchLeaf.setViewState({
      type: "search",
      state: { ...this.state, triggerBySelf: true }
    });
    setTimeout(async () => {
      var _a2, _b2, _c2;
      await this.searchLeaf.view.setState({ ...this.state, triggerBySelf: true }, { history: false });
      const searchComponent = this.searchLeaf.view.searchComponent;
      if (searchComponent == null ? void 0 : searchComponent.inputEl) {
        ((_a2 = this.state) == null ? void 0 : _a2.current) ? searchComponent.inputEl.setSelectionRange(0, 0) : searchComponent.inputEl.setSelectionRange(0, (_c2 = (_b2 = this.state) == null ? void 0 : _b2.query) == null ? void 0 : _c2.length);
      }
    }, 0);
    return;
  }
  initInput(retries = 10) {
    const inputEl = this.contentEl.getElementsByTagName("input")[0];
    if (!inputEl) {
      if (retries > 0) {
        setTimeout(() => this.initInput(retries - 1), 50);
      }
      return;
    }
    inputEl.focus();
    inputEl.onkeydown = (e) => {
      var _a2, _b2, _c2;
      const currentView = this.searchLeaf.view;
      switch (e.key) {
        case "ArrowDown":
        case "n":
          if (e.key === "n" && !e.ctrlKey)
            break;
          if (e.key === "n")
            e.preventDefault();
          if (e.shiftKey) {
            currentView.onKeyShowMoreAfter(e);
            if (currentView.dom.focusedItem) {
              if (currentView.dom.focusedItem.collapsible) {
                currentView.dom.focusedItem.setCollapse(false);
              }
              this.focusdItem = currentView.dom.focusedItem;
            }
          } else {
            currentView.onKeyArrowDownInFocus(e);
            this.focusdItem = currentView.dom.focusedItem;
            this.debouncedAutoPreview();
          }
          break;
        case "ArrowUp":
        case "p":
          if (e.key === "p" && !e.ctrlKey)
            break;
          if (e.key === "p")
            e.preventDefault();
          if (e.shiftKey) {
            currentView.onKeyShowMoreBefore(e);
            if (currentView.dom.focusedItem) {
              if (currentView.dom.focusedItem.collapseEl) {
                currentView.dom.focusedItem.setCollapse(true);
              }
              this.focusdItem = currentView.dom.focusedItem;
            }
          } else {
            currentView.onKeyArrowUpInFocus(e);
            this.focusdItem = currentView.dom.focusedItem;
            if (!currentView.dom.focusedItem.content) {
              this.focusdItem = void 0;
            }
            this.debouncedAutoPreview();
          }
          break;
        case "ArrowLeft":
          currentView.onKeyArrowLeftInFocus(e);
          break;
        case "ArrowRight":
          currentView.onKeyArrowRightInFocus(e);
          break;
        case "Enter":
          if (import_obsidian2.Keymap.isModifier(e, "Mod") && import_obsidian2.Keymap.isModifier(e, "Shift") && !this.focusdItem) {
            e.preventDefault();
            const fileName = inputEl.value.trim();
            const real = fileName.replace(/[/\\?%*:|"<>]/g, "-");
            this.plugin.app.workspace.openLinkText(real, "", true);
            this.close();
            break;
          }
          currentView.onKeyEnterInFocus(e);
          if (e.altKey && currentView.dom.focusedItem) {
            this.close();
          }
          break;
        case "Tab":
          e.preventDefault();
          if (e.shiftKey) {
            if (this.fileLeaf) {
              (_a2 = this.fileLeaf) == null ? void 0 : _a2.detach();
              this.fileLeaf = void 0;
              (_b2 = this.fileEmbeddedView) == null ? void 0 : _b2.unload();
              this.modalEl.toggleClass("float-search-width", false);
              this.fileEl.detach();
              break;
            }
          }
          if (currentView.dom.focusedItem) {
            const item = currentView.dom.focusedItem;
            const file = item.parent.file instanceof import_obsidian2.TFile ? item.parent.file : item.file;
            item.parent.file instanceof import_obsidian2.TFile ? this.initFileView(file, {
              match: {
                content: item.content,
                matches: item.matches
              }
            }) : this.initFileView(file, void 0);
          }
          break;
        case "e":
          if (e.ctrlKey) {
            e.preventDefault();
            if (this.fileLeaf) {
              const estate = this.fileLeaf.getViewState();
              estate.state = {
                ...estate.state,
                mode: ((_c2 = estate.state) == null ? void 0 : _c2.mode) === "preview" ? "source" : "preview"
              };
              this.fileLeaf.setViewState(estate, {
                focus: true
              });
              setTimeout(() => {
                var _a3, _b3;
                (_b3 = (_a3 = this.searchLeaf.view.searchComponent) == null ? void 0 : _a3.inputEl) == null ? void 0 : _b3.focus();
              }, 0);
            }
          }
          break;
        case "g":
          if (this.fileLeaf && e.ctrlKey) {
            e.preventDefault();
            this.plugin.app.workspace.setActiveLeaf(this.fileLeaf, {
              focus: true
            });
          }
          break;
        case "C":
          if (e.ctrlKey && e.shiftKey) {
            e.preventDefault();
            const text = currentView.dom.focusedItem.el.innerText;
            navigator.clipboard.writeText(text);
          }
          break;
      }
    };
  }
  autoPreviewFocusedItem() {
    var _a2, _b2, _c2;
    const currentView = this.searchLeaf.view;
    const item = (_a2 = currentView.dom) == null ? void 0 : _a2.focusedItem;
    if (!item)
      return;
    const file = ((_b2 = item.parent) == null ? void 0 : _b2.file) instanceof import_obsidian2.TFile ? item.parent.file : item.file;
    if (!(file instanceof import_obsidian2.TFile))
      return;
    const state = ((_c2 = item.parent) == null ? void 0 : _c2.file) instanceof import_obsidian2.TFile ? {
      match: {
        content: item.content,
        matches: item.matches
      }
    } : void 0;
    this.initFileView(file, state);
  }
  initContent() {
    const { contentEl } = this;
    contentEl.onclick = (e) => {
      var _a2, _b2;
      const resultElement = contentEl.getElementsByClassName("search-results-children")[0];
      if (resultElement.children.length < 2) {
        return;
      }
      let targetElement = e.target;
      if (e.altKey || !this.fileLeaf) {
        while (targetElement) {
          if (targetElement.classList.contains("tree-item-icon")) {
            break;
          }
          if (targetElement.classList.contains("search-result-hover-button")) {
            break;
          }
          if (targetElement.classList.contains("tree-item")) {
            this.close();
            break;
          }
          targetElement = targetElement.parentElement;
        }
        return;
      }
      if (this.fileLeaf) {
        const currentView = this.searchLeaf.view;
        if (this.searchCtnEl.contains(targetElement)) {
          while (targetElement) {
            if (targetElement.classList.contains("tree-item")) {
              break;
            }
            targetElement = targetElement.parentElement;
          }
          if (!targetElement)
            return;
          const fileInnerEl = targetElement == null ? void 0 : targetElement.getElementsByClassName("tree-item-inner")[0];
          const innerText = fileInnerEl.innerText;
          const file = this.plugin.app.metadataCache.getFirstLinkpathDest(innerText, "");
          if (file) {
            const item = currentView.dom.resultDomLookup.get(file);
            currentView.dom.setFocusedItem(item);
            this.initFileView(file, void 0);
            (_b2 = (_a2 = this.searchLeaf.view.searchComponent) == null ? void 0 : _a2.inputEl) == null ? void 0 : _b2.focus();
          }
        }
        return;
      }
    };
  }
  async initFileView(file, state) {
    var _a2, _b2, _c2, _d2, _e;
    if (this.fileLeaf) {
      await this.fileLeaf.openFile(file, {
        active: false,
        eState: state
      });
      if (((_b2 = (_a2 = this.fileState) == null ? void 0 : _a2.match) == null ? void 0 : _b2.matches[0]) === ((_c2 = state == null ? void 0 : state.match) == null ? void 0 : _c2.matches[0]) && state && this.fileState) {
        setTimeout(() => {
          if (this.fileLeaf) {
            this.plugin.app.workspace.setActiveLeaf(this.fileLeaf, {
              focus: true
            });
          }
        }, 0);
      } else {
        this.fileState = state;
        setTimeout(() => {
          var _a3, _b3;
          (_b3 = (_a3 = this.searchLeaf.view.searchComponent) == null ? void 0 : _a3.inputEl) == null ? void 0 : _b3.focus();
        }, 0);
      }
      return;
    }
    const { contentEl } = this;
    this.fileEl = contentEl.createDiv({
      cls: "float-search-modal-file-ctn"
    });
    this.modalEl.toggleClass("float-search-width", true);
    this.fileEl.onkeydown = (e) => {
      var _a3, _b3, _c3, _d3;
      if (e.ctrlKey && e.key === "g") {
        e.preventDefault();
        e.stopPropagation();
        (_b3 = (_a3 = this.searchLeaf.view.searchComponent) == null ? void 0 : _a3.inputEl) == null ? void 0 : _b3.focus();
      }
      if (e.key === "Tab" && e.ctrlKey) {
        e.preventDefault();
        e.stopPropagation();
        (_d3 = (_c3 = this.searchLeaf.view.searchComponent) == null ? void 0 : _c3.inputEl) == null ? void 0 : _d3.focus();
      }
    };
    if (!this.fileEl)
      return;
    const [createdLeaf, embeddedView] = spawnLeafView(this.plugin, this.fileEl);
    this.fileLeaf = createdLeaf;
    this.fileEmbeddedView = embeddedView;
    this.fileLeaf.setPinned(true);
    await this.fileLeaf.openFile(file, {
      active: false,
      eState: state
    });
    this.fileState = state;
    (_e = (_d2 = this.searchLeaf.view.searchComponent) == null ? void 0 : _d2.inputEl) == null ? void 0 : _e.focus();
  }
};
var FloatSearchCmdkModal = class extends import_obsidian2.SuggestModal {
  constructor(plugin) {
    super(plugin.app);
    this.searchAbort = null;
    this.onSelectedChange = (0, import_obsidian3.debounce)((result, _evt) => {
      if (result == null ? void 0 : result.file)
        this.showPreview(result);
    }, 100);
    this.plugin = plugin;
    this.limit = 50;
    this.setPlaceholder("Search files and content...");
    this.setInstructions([
      { command: "\u2191\u2193", purpose: "Navigate" },
      { command: "\u21B5", purpose: "Open" },
      { command: "Shift \u21B5", purpose: "New tab" },
      { command: "esc", purpose: "Close" }
    ]);
    this.modalEl.addClass("float-search-cmdk");
    this.containerEl.addClass("float-search-cmdk-container");
  }
  onOpen() {
    super.onOpen();
    this.bodyEl = createDiv("float-search-cmdk-body");
    this.modalEl.insertBefore(this.bodyEl, this.resultContainerEl);
    this.bodyEl.appendChild(this.resultContainerEl);
  }
  getSuggestions(_query) {
    return [];
  }
  updateSuggestions() {
    var _a2;
    (_a2 = this.searchAbort) == null ? void 0 : _a2.abort();
    const abort = this.searchAbort = new AbortController();
    const { signal } = abort;
    const chooser = this.chooser;
    const query = this.inputEl.value;
    const files = this.app.vault.getFiles().filter((f) => f.extension === "md" || f.extension === "canvas" || f.extension === "pdf");
    if (!query.trim()) {
      const recent = files.sort((a, b) => b.stat.mtime - a.stat.mtime).slice(0, this.limit).map((file) => ({
        file,
        nameMatch: null,
        pathMatch: null,
        type: "file"
      }));
      chooser.setSuggestions(recent);
      return;
    }
    const fuzzy = (0, import_obsidian2.prepareFuzzySearch)(query);
    const fileResults = [];
    for (const file of files) {
      const nameMatch = fuzzy(file.basename);
      const pathMatch = fuzzy(file.path);
      if (nameMatch || pathMatch) {
        fileResults.push({
          file,
          nameMatch,
          pathMatch,
          type: "file"
        });
      }
    }
    fileResults.sort((a, b) => {
      var _a3, _b2, _c2, _d2, _e, _f, _g, _h;
      const sa = Math.max((_b2 = (_a3 = a.nameMatch) == null ? void 0 : _a3.score) != null ? _b2 : -Infinity, ((_d2 = (_c2 = a.pathMatch) == null ? void 0 : _c2.score) != null ? _d2 : -Infinity) * 0.5);
      const sb = Math.max((_f = (_e = b.nameMatch) == null ? void 0 : _e.score) != null ? _f : -Infinity, ((_h = (_g = b.pathMatch) == null ? void 0 : _g.score) != null ? _h : -Infinity) * 0.5);
      return sb - sa;
    });
    chooser.setSuggestions(fileResults.slice(0, this.limit));
    if (query.trim().length >= 2) {
      this.progressiveHeadingSearch(files, fuzzy, chooser, signal);
      this.progressiveContentSearch(files, query, chooser, signal);
    }
  }
  progressiveHeadingSearch(files, fuzzy, chooser, signal) {
    const BATCH_SIZE = 50;
    let idx = 0;
    let added = 0;
    const MAX_HEADING_RESULTS = 20;
    const processBatch = () => {
      if (signal.aborted)
        return;
      const end = Math.min(idx + BATCH_SIZE, files.length);
      for (; idx < end; idx++) {
        if (added >= MAX_HEADING_RESULTS)
          return;
        const file = files[idx];
        const cache = this.app.metadataCache.getFileCache(file);
        if (!(cache == null ? void 0 : cache.headings))
          continue;
        for (const h of cache.headings) {
          const headingMatch = fuzzy(h.heading);
          if (headingMatch) {
            chooser.addSuggestion({
              file,
              nameMatch: null,
              pathMatch: null,
              heading: h.heading,
              headingMatch,
              type: "heading"
            });
            added++;
            if (added >= MAX_HEADING_RESULTS)
              return;
          }
        }
      }
      if (idx < files.length && added < MAX_HEADING_RESULTS) {
        setTimeout(processBatch, 0);
      }
    };
    setTimeout(processBatch, 0);
  }
  progressiveContentSearch(files, query, chooser, signal) {
    const BATCH_SIZE = 50;
    const MAX_CONTENT_RESULTS = 20;
    const DURATION_LIMIT = 5;
    const simpleSearch = (0, import_obsidian2.prepareSimpleSearch)(query);
    let idx = 0;
    let added = 0;
    const processBatch = async () => {
      if (signal.aborted)
        return;
      const start = performance.now();
      for (; idx < files.length; idx++) {
        if (signal.aborted || added >= MAX_CONTENT_RESULTS)
          return;
        if (idx % BATCH_SIZE === 0 && idx > 0) {
          if (performance.now() - start > DURATION_LIMIT) {
            setTimeout(processBatch, 0);
            return;
          }
        }
        const file = files[idx];
        if (file.extension !== "md")
          continue;
        let text;
        try {
          text = await this.app.vault.cachedRead(file);
        } catch (e) {
          continue;
        }
        const result = simpleSearch(text);
        if (!result)
          continue;
        const matchStart = result.matches[0][0];
        let line = 0;
        let lineStart = 0;
        for (let i = 0; i < matchStart; i++) {
          if (text.charCodeAt(i) === 10) {
            line++;
            lineStart = i + 1;
          }
        }
        let lineEnd = text.indexOf("\n", lineStart);
        if (lineEnd === -1)
          lineEnd = text.length;
        const lineText = text.substring(lineStart, lineEnd).trim();
        const lineMatch = simpleSearch(lineText);
        chooser.addSuggestion({
          file,
          nameMatch: null,
          pathMatch: null,
          content: lineText,
          contentMatch: lineMatch,
          line,
          type: "content"
        });
        added++;
        if (added >= MAX_CONTENT_RESULTS)
          return;
      }
    };
    setTimeout(processBatch, 50);
  }
  renderSuggestion(result, el) {
    var _a2;
    el.addClass("mod-complex");
    const contentEl = el.createDiv("suggestion-content");
    if (result.type === "content" && result.content) {
      const titleEl = contentEl.createDiv("suggestion-title");
      if (result.contentMatch) {
        (0, import_obsidian2.renderResults)(titleEl, result.content, result.contentMatch);
      } else {
        titleEl.setText(result.content);
      }
      const noteEl = contentEl.createDiv("suggestion-note");
      noteEl.setText(result.file.path);
    } else if (result.type === "heading" && result.heading) {
      const titleEl = contentEl.createDiv("suggestion-title");
      if (result.headingMatch) {
        (0, import_obsidian2.renderResults)(titleEl, result.heading, result.headingMatch);
      } else {
        titleEl.setText(result.heading);
      }
      const noteEl = contentEl.createDiv("suggestion-note");
      noteEl.setText(result.file.path);
    } else {
      const titleEl = contentEl.createDiv("suggestion-title");
      if (result.nameMatch) {
        (0, import_obsidian2.renderResults)(titleEl, result.file.basename, result.nameMatch);
      } else {
        titleEl.setText(result.file.basename);
      }
      const noteEl = contentEl.createDiv("suggestion-note");
      const parentPath = ((_a2 = result.file.parent) == null ? void 0 : _a2.path) || "/";
      if (result.pathMatch) {
        (0, import_obsidian2.renderResults)(noteEl, parentPath, result.pathMatch);
      } else {
        noteEl.setText(parentPath);
      }
    }
    if (result.file.extension !== "md") {
      el.createDiv("suggestion-aux").createSpan("suggestion-flair").setText(result.file.extension);
    }
  }
  onChooseSuggestion(result, evt) {
    var _a2;
    const leaf = import_obsidian2.Keymap.isModEvent(evt) ? this.app.workspace.getLeaf("tab") : (_a2 = this.app.workspace.getMostRecentLeaf()) != null ? _a2 : this.app.workspace.getLeaf();
    const eState = {};
    if (result.type === "heading" && result.heading) {
      eState.subpath = "#" + result.heading;
    } else if (result.type === "content" && result.line != null) {
      eState.line = result.line;
    }
    leaf.setViewState({
      type: result.file.extension === "pdf" ? "pdf" : "markdown",
      state: { file: result.file.path },
      active: true
    }).then(() => {
      if (eState.subpath || eState.line != null) {
        leaf.setEphemeralState(eState);
      }
    });
  }
  async showPreview(result) {
    if (!this.previewEl) {
      this.previewEl = this.bodyEl.createDiv("float-search-cmdk-preview");
      this.modalEl.addClass("float-search-cmdk-expanded");
      const [leaf, view] = spawnLeafView(this.plugin, this.previewEl);
      this.fileLeaf = leaf;
      this.fileEmbeddedView = view;
      this.fileLeaf.setPinned(true);
    }
    const file = result.file;
    await this.fileLeaf.openFile(file, { active: false });
    const eState = {};
    if (result.type === "heading" && result.heading) {
      eState.subpath = "#" + result.heading;
    } else if (result.type === "content" && result.line != null) {
      eState.line = result.line;
    }
    if (eState.subpath || eState.line != null) {
      this.fileLeaf.setViewState({
        type: file.extension === "pdf" ? "pdf" : "markdown",
        state: { file: file.path }
      }).then(() => {
        var _a2;
        (_a2 = this.fileLeaf) == null ? void 0 : _a2.setEphemeralState(eState);
      });
    }
    this.inputEl.focus();
  }
  onClose() {
    var _a2, _b2;
    (_a2 = this.fileLeaf) == null ? void 0 : _a2.detach();
    (_b2 = this.fileEmbeddedView) == null ? void 0 : _b2.unload();
  }
};


/* nosourcemap */